@url = http://localhost:8080/api/location

### find By Id
GET {{url}}/1 HTTP/1.1

### Add
POST {{url}} HTTP/1/1
Content-Type: application/json

{
    "latitude": null,
    "longitude": -99.54321
}

### Update
PUT {{url}}/6 HTTP/1.1
Content-Type: application/json

{
    "locationId": 6,
    "latitude": 34.4567,
    "longitude": -99.9992
}

### Delete
DELETE {{url}}/4 HTTP/1.1