@url = http://localhost:8080/api/sighting

### find all
GET {{url}} HTTP/1.1

### find By Id
GET {{url}}/1 HTTP/1.1

### find By Cat Id
GET {{url}}/cat/2 HTTP/1.1

### Add
POST {{url}} HTTP/1/1
Content-Type: application/json

{
    "picture": "testsightingimg",
    "catDescription": "this is a cat",
    "sightingDescription": "this is a sighting",
    "sightingDate": "2021-05-20",
    "sightingTime": "18:50:12",
    "latitude": "44.947434",
    "longitude": "-93.666666",
    "usersId": 1,
    "catId": 1,
    "disabled": false
}

### Update
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "sightingId": 1,
    "picture": "/test/sighting/img",
    "catDescription": "this is a cat update",
    "sightingDescription": "this is a sighting update",
    "sightingDate": "2021-05-20",
    "sightingTime": "18:50:12",
    "latitude": "44.947434",
    "longitude": "-93.666666",
    "usersId": 3,
    "catId": 1,
    "disabled": false
}

### Delete
DELETE {{url}}/2 HTTP/1.1